#!/usr/bin/env ruby
# Takes lines of Ruby code, un-indents, checks syntax,
# outputs in Jekyll format for syntax highlighting.

code = STDIN.read

if code =~ /\A\s+/
  indent = $&
  code.gsub! /^#{indent}/, ''
end

code.gsub! /[ \t]+$/, ''

File.popen("ruby -wc >/dev/null", 'w') {|f| f << code }

puts "{% highlight ruby %}"
puts code
puts "{% endhighlight %}"
