#!/bin/sh
# Check ruby syntax in code examples

site="${1:-_site}"

exec ruby -rnokogiri -e '
  Nokogiri(ARGF).css("[data-lang=ruby]").each { |node|
    code = node.text
    File.popen("ruby -wc >/dev/null", "w"){|f| f << code }
    unless $?.success?
      puts "------ " + node.path
      puts code
      puts "======"
    end
  }' "$site"/book/*.html "$site"/dwemthy/index.html
